services:

  - type: web
    name: talent-scout-backend
    env: docker
    repo: https://github.com/onkar-2006/internship-assesment
    rootDir: backend  
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false  
    
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: talent-scout-backend
          property: host

  - type: web
    name: talent-scout-frontend
    env: docker
    repo: https://github.com/onkar-2006/internship-assesment
    rootDir: frontend 
    plan: free
    region: ohio
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: talent-scout-backend
          property: host
