services:
  # --- Backend Service ---
  - type: web
    name: talent-scout-backend
    env: docker
    repo: https://github.com/onkar-2006/internship-assesment
    rootDir: backend
    plan: free
    region: ohio
    envVars:
      - key: PORT
        value: 8000
      
      - fromGroup: talentscout-secrets
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: talent-scout-backend
          property: host

  
  - type: web
    name: talent-scout-frontend
    env: docker
    repo: https://github.com/onkar-2006/internship-assesment
    rootDir: frontend 
    plan: free
    region: ohio
    envVars:
      - fromGroup: talentscout-secrets
      - key: BACKEND_URL
        fromService:
          type: web
          name: talent-scout-backend
          property: host